CREATE DATABASE NOTA_FISCAL_NORMALIZADA;

USE NOTA_FISCAL_NORMALIZADA;

CREATE TABLE `NOTA_FISCAL` (
	`NRO_NOTA` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `NM_CLIENTE` VARCHAR(256) NOT NULL,
    `END_CLIENTE` VARCHAR(256) NOT NULL,
    `NM_VENDEDOR` VARCHAR(256) NOT NULL,
    `DT_EMISSAO` DATETIME DEFAULT CURRENT_TIMESTAMP,
    `VL_TOTAL` FLOAT NOT NULL
);

CREATE TABLE `PRODUTO` (
	`COD_PRODUTO` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`DESC_PRODUTO` VARCHAR(256) NOT NULL,
    `UN_MED` CHAR(2) NOT NULL,
    `VL_PRODUTO` FLOAT NOT NULL
);

CREATE TABLE `ITEM_NOTA_FISCAL` (
	`NRO_NOTA` INT NOT NULL,
    `COD_PRODUTO` INT NOT NULL,
    `QTD_PRODUTO` INT NOT NULL,
	`VL_PRECO` FLOAT NOT NULL,
    `VL_TOTAL` FLOAT NOT NULL,
    PRIMARY KEY (NRO_NOTA, COD_PRODUTO), CONSTRAINT FK_NRO_NOTA_NOTA_FISCAL FOREIGN KEY (NRO_NOTA) REFERENCES NOTA_FISCAL (NRO_NOTA), 
    CONSTRAINT FK_COD_PRODUTO FOREIGN KEY (COD_PRODUTO) REFERENCES PRODUTO (COD_PRODUTO)
);

-- Produtos

INSERT INTO `PRODUTO` (DESC_PRODUTO, UN_MED, VL_PRODUTO) VALUES ('Arroz', 'KG', 5.00);
INSERT INTO `PRODUTO` (DESC_PRODUTO, UN_MED, VL_PRODUTO) VALUES ('Feijao', 'KG', 7.00);
INSERT INTO `PRODUTO` (DESC_PRODUTO, UN_MED, VL_PRODUTO) VALUES ('Macarrao', 'PC', 3.50);
INSERT INTO `PRODUTO` (DESC_PRODUTO, UN_MED, VL_PRODUTO) VALUES ('Óleo', 'LT', 6.50);

SELECT * FROM `PRODUTO`;

-- NOTA FISCAL

INSERT INTO `NOTA_FISCAL` (NM_CLIENTE, END_CLIENTE, NM_VENDEDOR, VL_TOTAL) VALUES ('Carlos', 'Florianópolis', 'Mariana', 200.00);
INSERT INTO `NOTA_FISCAL` (NM_CLIENTE, END_CLIENTE, NM_VENDEDOR, VL_TOTAL) VALUES ('Fernanda', 'Blumenau', 'Ricardo', 350.00);
INSERT INTO `NOTA_FISCAL` (NM_CLIENTE, END_CLIENTE, NM_VENDEDOR, VL_TOTAL) VALUES ('Lucas', 'Joinville', 'Patricia', 500.00);
INSERT INTO `NOTA_FISCAL` (NM_CLIENTE, END_CLIENTE, NM_VENDEDOR, VL_TOTAL) VALUES ('Ana', 'Itajaí', 'Fernando', 420.00);
INSERT INTO `NOTA_FISCAL` (NM_CLIENTE, END_CLIENTE, NM_VENDEDOR, VL_TOTAL) VALUES ('Rafael', 'Balneário Camboriú', 'Juliana', 300.00);

SELECT * FROM `NOTA_FISCAL`;

-- ITENS NOTA FISCAL

-- Itens da Nota 01

INSERT INTO `ITEM_NOTA_FISCAL` (NRO_NOTA, COD_PRODUTO, QTD_PRODUTO, VL_PRECO, VL_TOTAL) VALUES (1, 1, 5, 5.00, 25.00);
INSERT INTO `ITEM_NOTA_FISCAL` (NRO_NOTA, COD_PRODUTO, QTD_PRODUTO, VL_PRECO, VL_TOTAL) VALUES (1, 2, 10, 7.00, 70.00);
INSERT INTO `ITEM_NOTA_FISCAL` (NRO_NOTA, COD_PRODUTO, QTD_PRODUTO, VL_PRECO, VL_TOTAL) VALUES (1, 3, 15, 3.50, 52.50);
INSERT INTO `ITEM_NOTA_FISCAL` (NRO_NOTA, COD_PRODUTO, QTD_PRODUTO, VL_PRECO, VL_TOTAL) VALUES (1, 4, 8, 6.50, 52.00);

-- Itens da Nota 02

INSERT INTO `ITEM_NOTA_FISCAL` (NRO_NOTA, COD_PRODUTO, QTD_PRODUTO, VL_PRECO, VL_TOTAL) VALUES (2, 1, 20, 5.00, 100.00);
INSERT INTO `ITEM_NOTA_FISCAL` (NRO_NOTA, COD_PRODUTO, QTD_PRODUTO, VL_PRECO, VL_TOTAL) VALUES (2, 2, 15, 7.00, 105.00);
INSERT INTO `ITEM_NOTA_FISCAL` (NRO_NOTA, COD_PRODUTO, QTD_PRODUTO, VL_PRECO, VL_TOTAL) VALUES (2, 3, 10, 3.50, 35.00);
INSERT INTO `ITEM_NOTA_FISCAL` (NRO_NOTA, COD_PRODUTO, QTD_PRODUTO, VL_PRECO, VL_TOTAL) VALUES (2, 4, 16, 6.50, 104.00);

-- Itens da Nota 03

INSERT INTO `ITEM_NOTA_FISCAL` (NRO_NOTA, COD_PRODUTO, QTD_PRODUTO, VL_PRECO, VL_TOTAL) VALUES (3, 1, 30, 5.00, 150.00);
INSERT INTO `ITEM_NOTA_FISCAL` (NRO_NOTA, COD_PRODUTO, QTD_PRODUTO, VL_PRECO, VL_TOTAL) VALUES (3, 2, 25, 7.00, 175.00);
INSERT INTO `ITEM_NOTA_FISCAL` (NRO_NOTA, COD_PRODUTO, QTD_PRODUTO, VL_PRECO, VL_TOTAL) VALUES (3, 3, 20, 3.50, 70.00);
INSERT INTO `ITEM_NOTA_FISCAL` (NRO_NOTA, COD_PRODUTO, QTD_PRODUTO, VL_PRECO, VL_TOTAL) VALUES (3, 4, 16, 6.50, 104.00);

-- Itens da Nota 04

INSERT INTO `ITEM_NOTA_FISCAL` (NRO_NOTA, COD_PRODUTO, QTD_PRODUTO, VL_PRECO, VL_TOTAL) VALUES (4, 1, 10, 5.00, 50.00);
INSERT INTO `ITEM_NOTA_FISCAL` (NRO_NOTA, COD_PRODUTO, QTD_PRODUTO, VL_PRECO, VL_TOTAL) VALUES (4, 2, 12, 7.00, 84.00);
INSERT INTO `ITEM_NOTA_FISCAL` (NRO_NOTA, COD_PRODUTO, QTD_PRODUTO, VL_PRECO, VL_TOTAL) VALUES (4, 3, 8, 3.50, 28.00);
INSERT INTO `ITEM_NOTA_FISCAL` (NRO_NOTA, COD_PRODUTO, QTD_PRODUTO, VL_PRECO, VL_TOTAL) VALUES (4, 4, 15, 6.50, 97.50);

SELECT * FROM `ITEM_NOTA_FISCAL`;



SELECT * FROM PRODUTO WHERE COD_PRODUTO = 3;

-- UPDATE, ATUALIZANDO DADOS DE COLUNAS EM TABELAS

UPDATE PRODUTO
SET VL_PRODUTO = 5.5, DESC_PRODUTO = 'ATUALIZADO',
UN_MED = 'PC'
WHERE COD_PRODUTO = 3;

-- DELETE, EXCLUINDO REGISTROS DE TABELAS

DELETE FROM PRODUTO
WHERE COD_PRODUTO = 3;
-- NESTE CASO UMA EXCEÇÃO SERA LANÇADA
-- VIOLAÇÃO DA CONSTRAINT QUE AMARRA O PRODUTO AO ITEM DA NOTA FISCAL, NÃO PE POSSIVEL EXCLUIR UMA PK QUE TEM DEPENDENSIAS EM FKS

INSERT INTO PRODUTO (DESC_PRODUTO, UN_MED, VL_PRODUTO) VALUES ('Teste delete', 'LT', 5.50);

SELECT * FROM PRODUTO;

DELETE FROM PRODUTO WHERE COD_PRODUTO = 5;



