USE VETERYNARY;

-- A) Qual a quantidade de animais registradas no sistema?
SELECT 
	COUNT(*) AS ANIMAL_COUNT
FROM 
	ANIMAL;

-- B) Qual o total de vacinas aplicadas registradas no sistema?
SELECT 
	COUNT(*) AS TOTAL_VACCINES
FROM 
	VACCINE;
    
-- C) Quantos animais temos agrupados registrados para cada categoria?
SELECT TYP.SPECIE, COUNT(AN.ID) AS TOTAL
FROM 
	ANIMAL AS AN
    INNER JOIN 
		ANIMAL_TYPE AS TYP ON TYP.ID = AN.ANIMAL_TYPE_ID
GROUP BY TYP.SPECIE
ORDER BY TOTAL DESC, TYP.SPECIE ASC;
-- Primeiro ordena pelo total, dps pelo nome

-- D) Qual a categoria de animais de mais vacinas recebeu?
SELECT TYP.SPECIE, COUNT(VA.ID) AS NUM_VACCINE
FROM
	ANIMAL_TYPE AS TYP
	INNER JOIN 
		ANIMAL AS AN ON AN.ANIMAL_TYPE_ID = TYP.ID
    INNER JOIN
		VACCINE AS VA ON VA.ANIMAL_ID = AN.ID
GROUP BY TYP.SPECIE
ORDER BY NUM_VACCINE DESC;

-- Extra
-- E) Numero de animais vacinados
SELECT COUNT(VA.ANIMAL_ID) AS ANIMALS_VACCINATED
FROM VACCINE AS VA
INNER JOIN ANIMAL AS AN ON VA.ANIMAL_ID = AN.ID;

-- F) Retorne o nome do animal mais pesado de cada especie
SELECT TPY.SPECIE, AN.A_NAME, MAX(AN.WEIGHT) AS AN_WEIGHT
FROM
	ANIMAL AS AN
    INNER JOIN
		ANIMAL_TYPE AS TPY ON AN.ANIMAL_TYPE_ID = TPY.ID
GROUP BY TPY.SPECIE, AN.A_NAME
ORDER BY AN_WEIGHT DESC, TPY.SPECIE ASC, AN.A_NAME ASC;

-- G) Retorne as 5 primeiras vacinas aplicadas
SELECT VA.VACCINE_NAME, TPY.SPECIE,  VA.VACCINE_DATE
FROM
	VACCINE AS VA
	INNER JOIN
		ANIMAL AS AN ON VA.ANIMAL_ID = AN.ID
	INNER JOIN
		ANIMAL_TYPE AS TPY ON AN.ANIMAL_TYPE_ID = TPY.ID
GROUP BY VA.ID
ORDER BY VA.VACCINE_DATE DESC
LIMIT 5;
-- Usando 2 joins porque VACCINE nao possui relacao direta com ANIMAl_TYPE

/*
-- Versao com data formata para estilo brasileiro
SELECT VA.VACCINE_NAME, TPY.SPECIE, DATE_FORMAT(VA.VACCINE_DATE, '%d/%m/%Y') AS FORMATTED_DATE
FROM VACCINE AS VA
INNER JOIN ANIMAL AS AN ON VA.ANIMAL_ID = AN.ID
INNER JOIN ANIMAL_TYPE AS TPY ON AN.ANIMAL_TYPE_ID = TPY.ID
ORDER BY VA.VACCINE_DATE DESC
LIMIT 5;
*/

-- H) Retorne a altura media dos felinos
SELECT TYP.SPECIE, AVG(AN.HEIGHT) AS AVG_HEIGHT
FROM 
	ANIMAL AS AN
    INNER JOIN
		ANIMAL_TYPE AS TYP ON AN.ID = TYP.ID
WHERE TYP.SPECIE = 'Feline'
GROUP BY TYP.SPECIE
ORDER BY TYP.SPECIE;

-- I) Retorne a soma do peso dos bovinos
SELECT TYP.SPECIE, SUM(AN.WEIGHT) AS SUM_WEIGHT
FROM 
	ANIMAL AS AN
    INNER JOIN
		ANIMAL_TYPE AS TYP ON AN.ID = TYP.ID
WHERE TYP.SPECIE = 'Bovine'
GROUP BY TYP.SPECIE
ORDER BY TYP.SPECIE;

-- J) Retorne todo animal marrom
-- Data em formato americano
SELECT AN.A_NAME, TYP.SPECIE , AN.COLOR, AN.WEIGHT, AN.HEIGHT, DATE_FORMAT(AN.BIRTHDATE, '%m/%d/%Y') AS FORMATTED_DATE
FROM 
	ANIMAL AS AN
    INNER JOIN
		ANIMAL_TYPE AS TYP ON AN.ANIMAL_TYPE_ID = TYP.ID
WHERE AN.COLOR = 'Brown'
ORDER BY AN.A_NAME ASC;